version: '3.3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3200:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb