name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Run Coverage
      run: npm run coverage
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Run Integration Tests
      run: npm run test:integration
    - name: Run Backend Tests
      run: npm run test:backend
    - name: Run Frontend Tests
      run: npm run test:frontend
    - name: Run Performance Tests
      run: npm run test:performance
    - name: Publish Coverage
      run: |
        content=`node -pe 'JSON.stringify(process.argv[1])' "$(cat ./coverage/coverage-summary.json)"`
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -u leoduprates:${{ secrets.GIST_SECRET }} https://api.github.com/gists/80e2092dfa47c651009be8e7cbb3ef84 -d '{"files":{"javascript-testing-coverage.json":{"content": '"$content"'}}}'
